apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeview
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://code.benco.io/kubeview/deploy/helm
    chart: kubeview
    targetRevision: 1.0.20   
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
