apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: hiru-mgmt-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hiru-mgmt-operators
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: 'https://cloudnative-pg.github.io/charts'
    chart: cloudnative-pg
    targetRevision: 0.25.0
    helm:
      values: |
        # https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/README.md
        monitoring:
          grafanaDashboard:
            create: true
            namespace: hiru-mgmt-monitoring
          podMonitorEnabled: true
        
