apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hiru-mgmt-operators
  namespace: hiru-mgmt-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    argocd.argoproj.io/rootproject: "true"
spec:
  # Project description
  description: Project controlling cluster-wide operators not deployed as part of hiru-bootstrap

  # Allow manifests to deploy from only this Git repo or the app repo
  sourceRepos:
  - '*'

  sourceNamespaces:
  - '*'

  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'