apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  project: infra-project
  destination:
    namespace: postgres-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: 'https://cloudnative-pg.github.io/charts'
    chart: cloudnative-pg
    targetRevision: 0.24.0
    helm:
      values: |
        # https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/README.md
        monitoring:
          grafanaDashboard:
            create: true
            namespace: postgres-operator
          podMonitorEnabled: true
        