apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://cloudnative-pg.github.io/charts
  name: cloudnative-pg
